#!/bin/sh

#-:-:-:-:-:-:-:-:-:-:-:-:#
#    TIDoS Framework     #
#-:-:-:-:-:-:-:-:-:-:-:-:#

#This module requires TIDoS Framework
#https://github.com/0xInfection/TIDoS-Framework

# Update ur distro after of the installation.

# USE
# sudo apt-get update
# sudo apt-get upgrade

# environment dependencies
if ! hash libncurses5 2>/dev/null; then apt-get install --yes libncurses5 ; fi
if ! hash libxml2 2>/dev/null; then apt-get install --yes libxml2 ; fi
if ! hash nmap 2>/dev/null; then sudo apt-get install --yes nmap ; fi
if ! hash git 2>/dev/null; then sudo apt-get install --yes git ; fi
if ! hash tcpdump 2>/dev/null; then sudo apt-get install --yes tcpdump ; fi
if ! hash libexiv2-dev 2>/dev/null; then sudo apt-get install --yes libexiv2-dev ; fi
if ! hash build-essential 2>/dev/null; then sudo apt-get install --yes build-essential ; fi
if ! hash python-pip 2>/dev/null; then sudo apt-get install --yes python-pip ; fi
if ! hash python-xmpp 2>/dev/null; then sudo apt-get install --yes python-xmpp ; fi

# pip install stuffs (not suitable via source installations)
pip2 install sslyze
pip2 install tldextract
pip2 install lxml
pip2 install pillow
pip2 install ptyprocess
pip2 install mysql
pip2 install mysql-connector-python-rf
pip2 install dnslib

DIR=$(dirname $0)

# install from scratch
cd lib/setuptools/
sudo python2 bootstrap.py
sudo python2 setup.py install
cd ..
cd ..

cd lib/scapy_mod/
sudo python2 setup.py install
cd ..
cd ..

cd lib/pexpect_mod/
sudo python2 setup.py install
cd ..
cd ..

cd lib/idna_mod/
sudo python2 setup.py install
cd ..
cd ..

cd lib/bs4_mod/
sudo python2 setup.py install
cd ..
cd ..

cd lib/tld_mod/
sudo python2 setup.py install
cd ..
cd ..

cd lib/shodan_mod/
sudo python2 setup.py install
cd ..
cd ..

cd lib/requests_mod/
sudo python2 setup.py install
cd ..
cd ..

cd lib/pymap_mod/
sudo python2 setup.py install
cd ..
cd ..

cd lib/google_mod/
sudo python2 setup.py install
cd ..
cd ..

cd lib/emailprotectionslib_mod/
sudo python2 setup.py install
cd ..
cd ..

cd lib/builtwith_mod/
sudo python2 setup.py install
cd ..
cd ..

cd lib/mechanize_mod/
sudo python2 setup.py install
cd ..
cd ..

cd lib/pyexiv2_mod/
sudo python2 setup.py install
cd ..
cd ..
