#!/bin/sh

#-:-:-:-:-:-:-:-:-:-:-:-:#
#    TIDoS Framework     #
#-:-:-:-:-:-:-:-:-:-:-:-:#

#This module requires TIDoS Framework
#https://github.com/the-Infected-Drake/TIDoS-Framework 

#please update ur distro after of the installation. 

# USE 
# sudo apt-get update
# sudo apt-get upgrade

if ! hash libncurses5 2>/dev/null; then apt-get install --yes libncurses5 ; fi
if ! hash nmap 2>/dev/null; then sudo apt-get install --yes nmap ; fi
if ! hash build-essential 2>/dev/null; then sudo apt-get install --yes build-essential ; fi
if ! hash python-pip 2>/dev/null; then sudo apt-get install --yes python-pip ; fi
pip install sslscan

DIR=$(dirname $0)

cd lib/scapy/
sudo python setup.py install
cd ..
cd ..

cd lib/bs4/
sudo python setup.py install
cd .. 
cd .. 

cd lib/setuptools/
sudo python bootstrap.py
sudo python setup.py install
cd ..
cd ..

cd lib/wafw00f/
sudo python setup.py install
cd ..
cd ..

cd lib/nmap/
sudo python setup.py install
cd ..
cd ..

cd lib/google/
sudo python setup.py install
cd ..
cd ..

cd lib/lxml/
sudo python setup.py install
cd ..
cd ..
