#!/bin/sh

#-:-:-:-:-:-:-:-:-:-:-:-:#
#    TIDoS Framework     #
#-:-:-:-:-:-:-:-:-:-:-:-:#

#This module requires TIDoS Framework
#https://github.com/theInfectedDrake/TIDoS-Framework

# Update ur distro after of the installation.

# USE
# sudo apt-get update
# sudo apt-get upgrade

# environment dependencies
if ! hash libncurses5 2>/dev/null; then apt-get install --yes libncurses5 ; fi
if ! hash libxml2 2>/dev/null; then apt-get install --yes libxml2 ; fi
if ! hash nmap 2>/dev/null; then sudo apt-get install --yes nmap ; fi
if ! hash git 2>/dev/null; then sudo apt-get install --yes git ; fi
if ! hash tcpdump 2>/dev/null; then sudo apt-get install --yes tcpdump ; fi
if ! hash scons 2>/dev/null; then sudo apt-get install --yes scons ; fi
if ! hash libexiv2-dev 2>/dev/null; then sudo apt-get install --yes libexiv2-dev ; fi
if ! hash python-pyexiv2 2>/dev/null; then sudo apt-get install --yes python-pyexiv2 ; fi
if ! hash build-essential 2>/dev/null; then sudo apt-get install --yes build-essential ; fi
if ! hash python-pip 2>/dev/null; then sudo apt-get install --yes python-pip ; fi
if ! hash python-xmpp 2>/dev/null; then sudo apt-get install --yes python-xmpp ; fi
if ! hash default-libmysqlclient-dev 2>/dev/null; then sudo apt-get install --yes default-libmysqlclient-dev ; fi

# pip install stuffs (not suitable via source installations)
pip2 install sslyze
pip2 install tldextract
pip2 install lxml
pip2 install pillow

DIR=$(dirname $0)

# install from scratch
cd lib/setuptools/
sudo python2 bootstrap.py
sudo python2 setup.py install
cd ..
cd ..

cd lib/scapy/
sudo python2 setup.py install
cd ..
cd ..

cd lib/pexpect/
sudo python2 setup.py install
cd .. 
cd ..

cd lib/idna/
sudo python2 setup.py install
cd .. 
cd ..

cd lib/bs4/
sudo python2 setup.py install
cd .. 
cd .. 

cd lib/tld/
sudo python2 setup.py install
cd .. 
cd .. 

cd lib/shodan/
sudo python2 setup.py install
cd ..
cd ..

cd lib/requests/
sudo python2 setup.py install
cd ..
cd ..

cd lib/pymap/
sudo python2 setup.py install
cd ..
cd ..

cd lib/google/
sudo python2 setup.py install
cd ..
cd ..

cd lib/emailprotectionslib/
sudo python2 setup.py install
cd ..
cd ..

cd lib/mysql/
sudo python2 setup.py install
cd ..
cd ..

cd lib/builtwith/
sudo python2 setup.py install
cd ..
cd ..

cd lib/mechanize/
sudo python2 setup.py install
cd ..
cd ..

