#!/usr/bin/env python
# coding: utf-8

#-:-:-:-:-:-:-:-:-:-:-:-:#
#    TIDoS Framework     #
#-:-:-:-:-:-:-:-:-:-:-:-:#

#This module requires TIDoS Framework
#https://github.com/0xInfection/TIDoS-Framework

import os
import sys
import time
from core.Core.colors import *

print R+'\n   ==================='
print R+'    U N I N S T A L L'
print R+'   ===================\n' 
m = raw_input(O+' [#] Sure to remove TIDoS (y/N) :> ')
if m == 'y' or 'Y':
    try:
	time.sleep(0.5)
	print GR+'\nProceeding towards uninstallation...\n'
	time.sleep(1)
	print B+'Removing installation packages for TIDoS...'+C 
	os.system('rm -v -rf /opt/tidos-framework/ && rm -rf tidos/')
	time.sleep(1)
	print B+'Removing setup and executable files...'+C
	time.sleep(1)
	os.system('rm -v /usr/bin/tidos')
	time.sleep(0.4)
	print GR+'All installation packages have been removed...\n'
	time.sleep(0.4)
	print G+' [+] TIDoS-Framework has been successfully uninstalled...\n'
    except:
	print R+' [-] Something went wrong!'
	sys.exit(1)
else:
	print G+' [+] Good decision! :)'
	sys.exit(0)
