version: 2.0

flake8-steps: &steps
  - checkout
  #- run: sudo pip install -r requirements.txt
  - run: pip install --user flake8  # pytest
  - run: python -m flake8 --version ; pip --version
  # stop the build if there are Python syntax errors or undefined names
  - run: python -m flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide      
  - run: python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  #- run: pytest

jobs:
  Python2:
    docker:
      - image: circleci/python:2.7.15
    steps: *steps

  Python3:
    docker:
      - image: circleci/python:3.7.0
    steps: *steps

workflows:
  version: 2
  build:
    jobs:
      - Python2
      - Python3
