#!/usr/bin/env python3
# coding: utf-8

# -:-:-:-:-:-:-:-:-:-:-:-:#
#    TIDoS Framework     #
# -:-:-:-:-:-:-:-:-:-:-:-:#

# Author : @_tID
# This module requires TIDoS Framework
# https://github.com/0xInfection/TIDoS-Framework

patterns = ("<font face=\"Arial\" size=2>error \'800a0005\'</font>",
            "<h2> <i>Runtime Error</i> </h2></span>",
            "<p>Active Server Pages</font> <font face=\"Arial\" size=2>error \'ASP 0126\'</font>",
            "<TR><TD><H4>Error Diagnostic Information</H4><P><P>",
            "<li>Search the <a href=\"http://www.macromedia.com/support/coldfusion/\"",
            "target=\"new\">Knowledge Base</a> to find a solution to your problem.</li>",
            "Server.Execute Error",
            "Warning: opendir(Array):",
            "<H3>Original Exception: </H3>",
            "Server object error",
            "invalid literal for int()",
            "exceptions.ValueError",
            "<h2 style=\"font:8pt/11pt verdana; color:000000\">HTTP 403.6 - Forbidden: IP address rejected<br>",
            "<TITLE>500 Internal Server Error</TITLE>",
            "<b>warning</b>[/]\w\/\w\/\S*",
            "<b>Fatal error</b>:",
            "<b>Warning</b>:",
            "open_basedir restriction in effect",
            "<b> Description: </b>An unhandled exception occurred during the execution of the",
            "<H1>Error page exception</H1>",
            "<h2> <i>Runtime Error</i> </h2></span>",
            "<h2>Traceback <span>(innermost last)</span></h2>",
            "<h1 class=\"error_title\">Ruby on Rails application could not be started</h1>",
            "onclick=\"toggle(\'full exception chain stacktrace\')",
            "at org.apache.catalina",
            "at org.apache.coyote.",
            "<title>Error Occurred While Processing Request</title></head><body><p></p>",
            "<b>Fatal Error</b>",
            "\[an error occurred while processing this directive\]",
            "<HTML><HEAD><TITLE>Error Occurred While Processing Request</TITLE>",
            "Warning: session_start():",
            "PythonHandler django.core.handlers.modpython",
            "t = loader.get_template(template_name) # You need to create a 404.html template.",
            "<HTML><HEAD><TITLE>Error Occurred While Processing Request</TITLE></HEAD><BODY><HR><H3>",
            "<h2> <i>Access is denied</i> </h2></span>",
            "</HEAD><BODY><HR><H3>Error Occurred While Processing Request</H3><P>",
            "\[java.lang.",
            "class java.lang.",
            "java.lang.NullPointerException",
            "java.rmi.ServerException",
            "at java.lang.",
            "at org.apache.tomcat.",
            "The session id contains illegal characters",
            "\] does not contain handler parameter named",
            "eval()'d code</b> on line <b>",
            "at org.apache.jasper.",
            "<html><head><title>Application Exception</title>",
            "<p>Microsoft VBScript runtime </font>",
            "<font face=\"Arial\" size=2>error '800a000d'</font>",
            "<TITLE>nwwcgi Error",
            "Fatal error</b>:  preg_replace",
            "thrown in <b>",
            "Stack trace:",
            "</b> on line <b>")
