.TH "MKDOCS" "1" "10-May-2019" "1.0.4" "mkdocs Manual"
.SH NAME
mkdocs \- MkDocs - Project documentation with Markdown.
.SH SYNOPSIS
.B mkdocs
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
MkDocs - Project documentation with Markdown.
.SH OPTIONS
.TP
\fB\-V,\fP \-\-version
Show the version and exit.
.TP
\fB\-q,\fP \-\-quiet
Silence warnings
.TP
\fB\-v,\fP \-\-verbose
Enable verbose output
.SH COMMANDS
.PP
\fBserve\fP
  Run the builtin development server
  See \fBmkdocs-serve(1)\fP for full documentation on the \fBserve\fP command.
.PP
\fBbuild\fP
  Build the MkDocs documentation
  See \fBmkdocs-build(1)\fP for full documentation on the \fBbuild\fP command.
.PP
\fBgh-deploy\fP
  Deploy your documentation to GitHub Pages
  See \fBmkdocs-gh-deploy(1)\fP for full documentation on the \fBgh-deploy\fP command.
.PP
\fBnew\fP
  Create a new MkDocs project
  See \fBmkdocs-new(1)\fP for full documentation on the \fBnew\fP command.
