.TH "MKDOCS BUILD" "1" "10-May-2019" "1.0.4" "mkdocs build Manual"
.SH NAME
mkdocs\-build \- Build the MkDocs documentation
.SH SYNOPSIS
.B mkdocs build
[OPTIONS]
.SH DESCRIPTION
Build the MkDocs documentation
.SH OPTIONS
.TP
\fB\-c,\fP \-\-clean / \-\-dirty
Remove old files from the site_dir before building (the default).
.TP
\fB\-f,\fP \-\-config\-file FILENAME
Provide a specific MkDocs config
.TP
\fB\-s,\fP \-\-strict
Enable strict mode. This will cause MkDocs to abort the build on any warnings.
.TP
\fB\-t,\fP \-\-theme [mkdocs|readthedocs]
The theme to use when building your documentation.
.TP
\fB\-e,\fP \-\-theme\-dir PATH
The theme directory to use when building your documentation.
.TP
\fB\-d,\fP \-\-site\-dir PATH
The directory to output the result of the documentation build.
.TP
\fB\-q,\fP \-\-quiet
Silence warnings
.TP
\fB\-v,\fP \-\-verbose
Enable verbose output
