.TH "MKDOCS NEW" "1" "10-May-2019" "1.0.4" "mkdocs new Manual"
.SH NAME
mkdocs\-new \- Create a new MkDocs project
.SH SYNOPSIS
.B mkdocs new
[OPTIONS] PROJECT_DIRECTORY
.SH DESCRIPTION
Create a new MkDocs project
.SH OPTIONS
.TP
\fB\-q,\fP \-\-quiet
Silence warnings
.TP
\fB\-v,\fP \-\-verbose
Enable verbose output
