# -*- coding: utf-8 -*-

from TestsRunner import run_unit_tests

def tests_builder(target, source, env):
    result = run_unit_tests()
    if result.wasSuccessful():
        return None
    else:
        return result.errors + result.failures

env = Environment()
env.Command('test', None, tests_builder)

